/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.ModUsuario;
import static java.lang.System.exit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fercho
 */
public class V3PasosColocacionHw extends javax.swing.JPanel {

    /**
     * Creates new form V3PasosColocacionHw
     */
    int dispositivo = 1;
    ModUsuario usuario;
    boolean UsoHuella;

    public V3PasosColocacionHw(ModUsuario usuario, int dispositivo, boolean UsoHuella) {
        initComponents();
        this.usuario = usuario;
        this.dispositivo = dispositivo;
        configuracionBtn();
        cargarImagenes();
        this.UsoHuella = UsoHuella;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        contenedor_de_paneles = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        img1 = new javax.swing.JLabel();
        txt_paso1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        img2 = new javax.swing.JLabel();
        txt_paso2 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        img3 = new javax.swing.JLabel();
        txt_paso3 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        img4 = new javax.swing.JLabel();
        txt_paso4 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        img5 = new javax.swing.JLabel();
        txt_paso5 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_n_user = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(79, 84, 93));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pasos de colocación");
        add(jLabel2);
        jLabel2.setBounds(337, 100, 1160, 44);

        contenedor_de_paneles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        panel1.setLayout(null);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setText("Siguiente");
        jToggleButton1.setMaximumSize(new java.awt.Dimension(117, 25));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(117, 25));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        panel1.add(jToggleButton1);
        jToggleButton1.setBounds(1050, 0, 105, 660);

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/ajax-loader.gif"))); // NOI18N
        panel1.add(img1);
        img1.setBounds(110, 24, 340, 610);

        txt_paso1.setText("Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas \"Letraset\", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.");
        panel1.add(txt_paso1);
        txt_paso1.setBounds(470, 20, 560, 570);

        contenedor_de_paneles.addTab("Paso 1", panel1);

        panel2.setLayout(null);

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton4.setText("Anterior");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        panel2.add(jToggleButton4);
        jToggleButton4.setBounds(0, 0, 105, 660);

        jToggleButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton5.setText("Siguiente");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        panel2.add(jToggleButton5);
        jToggleButton5.setBounds(1050, 0, 105, 660);
        panel2.add(img2);
        img2.setBounds(110, 24, 340, 610);

        txt_paso2.setText("Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas \"Letraset\", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.");
        panel2.add(txt_paso2);
        txt_paso2.setBounds(470, 20, 560, 570);

        contenedor_de_paneles.addTab("Paso 2", panel2);

        panel3.setLayout(null);

        jToggleButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton6.setText("Anterior");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        panel3.add(jToggleButton6);
        jToggleButton6.setBounds(0, 0, 105, 660);

        jToggleButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton7.setText("Siguiente");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        panel3.add(jToggleButton7);
        jToggleButton7.setBounds(1050, 0, 105, 660);
        panel3.add(img3);
        img3.setBounds(110, 24, 340, 610);

        txt_paso3.setText("Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas \"Letraset\", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.");
        panel3.add(txt_paso3);
        txt_paso3.setBounds(470, 20, 560, 570);

        contenedor_de_paneles.addTab("Paso 3", panel3);

        panel4.setLayout(null);

        jToggleButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton8.setText("Anterior");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        panel4.add(jToggleButton8);
        jToggleButton8.setBounds(0, 0, 105, 660);

        jToggleButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton9.setText("Siguiente");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        panel4.add(jToggleButton9);
        jToggleButton9.setBounds(1050, 0, 105, 660);
        panel4.add(img4);
        img4.setBounds(110, 24, 340, 610);

        txt_paso4.setText("Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas \"Letraset\", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.");
        panel4.add(txt_paso4);
        txt_paso4.setBounds(470, 20, 560, 570);

        contenedor_de_paneles.addTab("Paso 4", panel4);

        panel5.setLayout(null);

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton3.setText("Anterior");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        panel5.add(jToggleButton3);
        jToggleButton3.setBounds(0, 0, 105, 660);
        panel5.add(img5);
        img5.setBounds(110, 24, 340, 610);

        txt_paso5.setText("Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas \"Letraset\", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.");
        panel5.add(txt_paso5);
        txt_paso5.setBounds(470, 20, 510, 570);

        contenedor_de_paneles.addTab("Paso 5", panel5);

        add(contenedor_de_paneles);
        contenedor_de_paneles.setBounds(340, 150, 1160, 690);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton2.setText("Finalizar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        add(jToggleButton2);
        jToggleButton2.setBounds(780, 850, 280, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_unsis.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(10, 10, 220, 220);

        jPanel2.setBackground(new java.awt.Color(79, 84, 93));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boy/hombre (3).png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(46, 40, 70, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bienvendido");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 150, 130, 17);

        lbl_n_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_n_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n_user.setText("Usuario: ");
        jPanel2.add(lbl_n_user);
        lbl_n_user.setBounds(0, 120, 150, 20);

        jLabel9.setBackground(new java.awt.Color(79, 84, 93));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/V2Colocacion/250 188.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 160, 200);

        add(jPanel2);
        jPanel2.setBounds(1700, 10, 150, 250);

        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras/flecha-hacia-la-izquierda (2).png"))); // NOI18N
        btn_atras.setToolTipText("Regresar");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        add(btn_atras);
        btn_atras.setBounds(910, 10, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/V2Colocacion/Untitled (2).png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(1630, 840, 230, 90);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/V4Principal/salida.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(1520, 870, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        avanzar_pestania();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        retroceder_pestania();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        avanzar_pestania();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        retroceder_pestania();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        avanzar_pestania();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        retroceder_pestania();
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        avanzar_pestania();
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        retroceder_pestania();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        IrVentanaColocacion();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed

        IrVentanaColocacion();

    }//GEN-LAST:event_btn_atrasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicación?", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void avanzar_pestania() {
        try {
            contenedor_de_paneles.setSelectedIndex(contenedor_de_paneles.getSelectedIndex() + 1);
        } catch (Exception e) {
            //System.out.println("Ya no hay más paneles");
        }
    }

    private void retroceder_pestania() {
        try {
            contenedor_de_paneles.setSelectedIndex(contenedor_de_paneles.getSelectedIndex() - 1);
        } catch (Exception e) {
            //System.out.println("Ya no hay más paneles");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JTabbedPane contenedor_de_paneles;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel lbl_n_user;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JLabel txt_paso1;
    private javax.swing.JLabel txt_paso2;
    private javax.swing.JLabel txt_paso3;
    private javax.swing.JLabel txt_paso4;
    private javax.swing.JLabel txt_paso5;
    // End of variables declaration//GEN-END:variables

    private void IrVentanaColocacion() {
        this.removeAll();
        this.updateUI();
        V2ColocacionHardware p = new V2ColocacionHardware(usuario, UsoHuella);
        p.setSize(1900, 1000);
        this.add(p);
        this.revalidate();
        this.repaint();
    }

    private void configuracionBtn() {

        lbl_n_user.setText(lbl_n_user.getText() + this.usuario.getUsuario_nombre());
        btn_atras.setContentAreaFilled(false);
        btn_atras.setBorder(null);
    }

    private void cargarImagenes() {
        if (dispositivo == 1) {
            System.out.println("Cargando Epoc");
            img1.setIcon(new ImageIcon("src/img/Colocar/Epoc/1.png"));
            img2.setIcon(new ImageIcon("src/img/Colocar/Epoc/2.png"));
            img3.setIcon(new ImageIcon("src/img/Colocar/Epoc/3.png"));
            img4.setIcon(new ImageIcon("src/img/Colocar/Epoc/4.png"));
            img5.setIcon(new ImageIcon("src/img/Colocar/Epoc/5.png"));
            
            String cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li >Colocar la solución salina en los orificios del estuche de los sensores</li>\n<br>"
                    + "<li >Colocar los sensores en cada orificio, de tal forma que se empape el fieltro de los sensores de solución</li>\n<br>"
                    + "</ol> </body></html>";
            txt_paso1.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"2\">Una vez empapado cada sensor se procede a colocarlo en el dispositivo Emotiv EPOC+</li>\n<br>"
                    + "</ol> </body></html>";
            txt_paso2.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"3\">Colocar el dispositivo de recolección de información USB del dispositivo Emotiv EPOC en la computadora</li>\n<br>"
                    + "</ol> </body></html>";
            txt_paso3.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"4\">Encender el dispositivo Emotiv EPOC+</li>\n<br>"
                   
                    + "</ol> </body></html>";
            txt_paso4.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"5\">Colocar el dispositivo Emotiv EPOC+ en el sujeto de pruebas</li>\n<br>"
                    + "</ol> </body></html>";
            txt_paso5.setText(cad);
        } else if (dispositivo == 2) {
            System.out.println("Cargando Ecg");
            img1.setIcon(new ImageIcon("src/img/Colocar/Ecg/1.png"));
            img2.setIcon(new ImageIcon("src/img/Colocar/Ecg/2.png"));
            img3.setIcon(new ImageIcon("src/img/Colocar/Ecg/3.jpg"));
            img4.setIcon(new ImageIcon("src/img/Colocar/Ecg/4.jpg"));
            img5.setIcon(new ImageIcon("src/img/Colocar/Ecg/5.png"));
            String cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li >Identificar las entradas analógicas, de voltaje y de conexión a tierra</li>\n<br>"
                    + "A: Las entradas de voltaje están descritas con 5V<br><br>"
                    + "B: Las entradas de conexión a tierra están descritas con GND<br><br>"
                    + "C: Las entradas analógicas están descritas por ANALOG IN"
                    + "</ol> </body></html>";
            txt_paso1.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"2\">Colocar el sensor de ritmo cardíaco en las entradas analógicas, de voltaje y de conexión a tierra correspondientes</li>\n<br>"
                    + "A: Colocar el pin macho del sensor en la entrada analógica A0 del arduino<br><br>"
                    + "B: Colocar el pin macho de conexión a tierra del sensor en un pin GND del arduino<br><br>"
                    + "C: Colocar el pin macho de conexión a voltaje del sensor a un pin 5V del arduino"
                    + "</ol> </body></html>";
            txt_paso2.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"3\">Verificar el estado de los cables del sensor</li>\n<br>"
                    + "- Asegure el dispositivo arduino en un punto donde no se efectúe movimiento"
                    + "</ol> </body></html>";
            txt_paso3.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"4\">Colocar el sensor en el dedo índice derecho del usuario</li>\n<br>"
                    + "- El sensor debe estar precionando el dedo del usuario"
                    + "</ol> </body></html>";
            txt_paso4.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"5\">Ingresar en el computador donde están conectados los sensores y realice las siguientes instrucciones</li>\n<br>"
                    + "<ol>"
                    + "<li>Dirigir la ubicación a la carpeta \"Calibración de Sensores SRC y GSR\"</li><br>"
                    + "<li>Compilar la aplicación con el comando \"gcc -o calibracion Calibración\\ del\\ Sensor.c\"</li><br>"
                    + "<li>Ejecutar el comando de superUsuario \"sudo su\"</li><br>"
                    + "<li>Escribir la contraseña de Administrador</li><br>"
                    + "<li>Para ejecutar la aplicación se utiliza el comando \"./calibración\"</li><br>"
                    + "<li>Una vez iniciado el programa nos solicita el modo de visualización de la información, <br>elegir 1) Datos crudos escribiendo \"1\" y pulsando ENTER</li><br>"
                    + "<li>Si todo marcha normal, se deben mostrar tres números provenientes desde arduino, en caso de rebibir el dato -9999 en alguna columna significa que algún sensor está dañado o desconectado</li><br>"
                    +"<br>Nota: La segunda y tercer columna corresponde al sensor"
                    + "</ol>"
                    + "</ol> </body></html>";
            txt_paso5.setText(cad);
        } else if (dispositivo == 3) {
            System.out.println("Cargando Gsr");
            img1.setIcon(new ImageIcon("src/img/Colocar/Gsr/1.png"));
            img2.setIcon(new ImageIcon("src/img/Colocar/Gsr/2.png"));
            img3.setIcon(new ImageIcon("src/img/Colocar/Gsr/3.jpg"));
            img4.setIcon(new ImageIcon("src/img/Colocar/Gsr/4.png"));
            img5.setIcon(new ImageIcon("src/img/Colocar/Gsr/5.png"));

            String cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li >Identificar las entradas analógicas, de voltaje y de conexión a tierra</li>\n<br>"
                    + "A: Las entradas de voltaje están descritas con 5V<br><br>"
                    + "B: Las entradas de conexión a tierra están descritas con GND<br><br>"
                    + "C: Las entradas analógicas están descritas por ANALOG IN"
                    + "</ol> </body></html>";
            txt_paso1.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"2\">Colocar el sensor de conductancia de la piel en las entradas analógicas, de voltaje y de conexión a tierra correspondientes</li>\n<br>"
                    + "A: Colocar el pin macho del sensor en la entrada analógica A1 del arduino<br><br>"
                    + "B: Colocar el pin macho de conexión a tierra del sensor en un pin GND del arduino<br><br>"
                    + "C: Colocar el pin macho de conexión a voltaje del sensor a un pin 5V del arduino"
                    + "</ol> </body></html>";
            txt_paso2.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"3\">Verificar el estado de los cables del sensor</li>\n<br>"
                    + "- Asegure el dispositivo arduino en un punto donde no se efectúe movimiento"
                    + "</ol> </body></html>";
            txt_paso3.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"4\">Colocar el sensor en el dedo índice izquierdo y el dedo medio izquierdo del usuario</li>\n<br>"
                    + "- Cada sensor debe estar precionando los dedos del usuario"
                    + "</ol> </body></html>";
            txt_paso4.setText(cad);
            cad = "<html><body><h2>Instrucciones:</h2> <ol>\n"
                    + "<li value=\"5\">Ingresar en el computador donde están conectados los sensores y realizar las siguientes instrucciones</li>\n<br>"
                    + "<ol>"
                    + "<li>Dirigir la ubicación a la carpeta \"Calibración de Sensores SRC y GSR\"</li><br>"
                    + "<li>Compilar la aplicación con el comando \"gcc -o calibracion Calibración\\ del\\ Sensor.c\"</li><br>"
                    + "<li>Ejecutar el comando de superUsuario \"sudo su\"</li><br>"
                    + "<li>Escribir la contraseña de Administrador</li><br>"
                    + "<li>Para ejecutar la aplicación se utiliza el comando \"./calibración\"</li><br>"
                    + "<li>Una vez iniciado el programa nos solicita el modo de visualización de la información, <br>elegir 1) Datos crudos escribiendo \"1\" y pulsando ENTER</li><br>"
                    + "<li>Si todo marcha normal, se deben mostrar tres números provenientes desde arduino, en caso de rebibir el dato -9999 en alguna columna significa que algún sensor está dañado o desconectado</li><br>"
                    +"<br>Nota: La primer columna corresponde al sensor"
                    + "</ol>"
                    + "</ol> </body></html>";
            txt_paso5.setText(cad);
        }
    }
}
